theme: jekyll-theme-slate
title: Shea E. Duarte
description: PhD Student in Perception, Cognition, & Cognitive Neuroscience, UC Davis
logo: ![profile](https://user-images.githubusercontent.com/33766275/103323790-3fbd7f80-49f9-11eb-9cb5-885438ef9e49.jpeg)
