theme: jekyll-theme-cayman
title: Shea E. Duarte
description: >
  PhD Student in Perception, Cognition, & Cognitive Neuroscience <br />
  University of California, Davis
avatar: profile.jpeg

  email: seduarte@ucdavis.edu
  twitter: sheaduarte
  github: sheaduarte
