theme: jekyll-theme-slate
title: Shea E. Duarte
description: PhD Student in Perception, Cognition, & Cognitive Neuroscience, UC Davis
avatar: bio-photo.jpg

  email: seduarte@ucdavis.edu
  twitter: sheaduarte
  github: sheaduarte
  
